### ISSUE TITLE
SelectFieldByIndex, this is available in madcow 1, needs to be available in madcow 2 too

### ISSUE THREAD

**Issue by AnchulAgrawal** [4impact/madcow#28]

**Comment by dawogfather** [comment]
This is actually already covered by SelectField when you use a number... i.e. 
```
myAwesomeDropDown.selectField = 1
```
should select the first option.

**Comment by dawogfather** [comment]
We will add the new 
```
myAwesomeDropDown.selectFieldByIndex = 1
```
and remove the ability for
```
myAwesomeDropDown.selectField = 1
``` 
to no longer select based on the index but rather on the value.

**Comment by dawogfather** [comment]
this is done and working now
